//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace totvs_sign_service_reports.Mocks {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("totvs_sign_service_reports.Mocks.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;data&quot;: [
        ///        {
        ///            &quot;codcoligada&quot;: 1,
        ///            &quot;chapa&quot;: &quot;00001&quot;,
        ///            &quot;nome&quot;: &quot;ITAMAR MENDES DA SILVEIRA&quot;,
        ///            &quot;salario&quot;: 3192.80
        ///        },
        ///        {
        ///            &quot;codcoligada&quot;: 1,
        ///            &quot;chapa&quot;: &quot;00003&quot;,
        ///            &quot;nome&quot;: &quot;MARIA CONCEICAO DE ASSIS&quot;,
        ///            &quot;salario&quot;: 5609.51
        ///        },
        ///        {
        ///            &quot;codcoligada&quot;: 1,
        ///            &quot;chapa&quot;: &quot;00008&quot;,
        ///            &quot;nome&quot;: &quot;ZELIA APARECIDA DA SILVA&quot;,
        ///            &quot;salario&quot;: 6787.51
        ///        [rest of string was truncated]&quot;;.
        /// </summary>
        public static string FuncionarioDataString {
            get {
                return ResourceManager.GetString("FuncionarioDataString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;name&quot;: &quot;9b8ef474-35be-48fc-88ae-cff2003e757c&quot;,
        ///  &quot;displayName&quot;: &quot;Objeto de Negócio sem Parâmetro&quot;,
        ///  &quot;description&quot;: &quot;Objeto de Teste Parâmetro&quot;,
        ///  &quot;areas&quot;: [
        ///    &quot;Mockoon&quot;
        ///  ],
        ///  &quot;schemaUrl&quot;: &quot;http://localhost:3002//api/bis/v1/native-provider/objects/9b8ef474-35be-48fc-88ae-cff2003e757c/schema&quot;,
        ///  &quot;dataUrl&quot;: &quot;http://localhost:3002//api/bis/v1/native-provider/objects/9b8ef474-35be-48fc-88ae-cff2003e757c/data/&quot;,
        ///  &quot;properties&quot;: [
        ///    {
        ///      &quot;name&quot;: &quot;chapa&quot;,
        ///      &quot;displayName&quot;: &quot;CHAPA&quot;,
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        public static string FuncionarioSchemaString {
            get {
                return ResourceManager.GetString("FuncionarioSchemaString", resourceCulture);
            }
        }
    }
}
